<template>
  <div class="wrapper">
    <div class="loadingio-spinner-bean-eater-c1mssxsmdfo">
      <div class="ldio-z4vv7maifvd">
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div>
          
          <div><article class="black_box"><span class="eye"></span></article></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
</template>


<style scoped>
.eye {
 display: block;
    width: 2px;
    height: 2px;
    background-color: red;
    top: 7px;
    left: 6px;
    border-radius: 2px;
    position: relative;
}
.black_box {
  display: block;
  position: relative ;
  width:15px ;
  height:15px ;
  background-color:white;
  top: 29px;
  left: 89px;
  border-radius: 10px
}
.wrapper {
  height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}
@keyframes ldio-z4vv7maifvd-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-z4vv7maifvd-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-z4vv7maifvd > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-z4vv7maifvd > div:nth-child(2) div {
  position: absolute;
  top: 40px;
  left: 40px;
  width: 120px;
  height: 60px;
  border-radius: 120px 120px 0 0;
  background: #fdf90e;
  animation: ldio-z4vv7maifvd-1 1s linear infinite;
  transform-origin: 60px 60px;
}
.ldio-z4vv7maifvd > div:nth-child(2) div:nth-child(2) {
  animation: ldio-z4vv7maifvd-2 1s linear infinite;
}
.ldio-z4vv7maifvd > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-z4vv7maifvd-3 {
  0% {
    transform: translate(190px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(70px, 0);
    opacity: 1;
  }
}
.ldio-z4vv7maifvd > div:nth-child(1) {
  display: block;
}
.ldio-z4vv7maifvd > div:nth-child(1) div {
  position: absolute;
  top: 92px;
  left: -8px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: #ffc300;
  animation: ldio-z4vv7maifvd-3 1s linear infinite;
}
.ldio-z4vv7maifvd > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-z4vv7maifvd > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-z4vv7maifvd > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-c1mssxsmdfo {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: fff;
}
.ldio-z4vv7maifvd {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-z4vv7maifvd div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
</style>